### PR TITLE
Changes to add fuel gauges and make CO2 Intakes match Hexcore parts Add Tags

### PR DESCRIPTION
**Pull request by Bornholio**
for Issues #19 & #21
adds draw gauge function to lqgMethane engines and removes scale and attachment modifiers for Intake parts

### CODE REVIEW

**Comment by Bornholio** [comment]
bulk added tags to all parts to allow searching
I may modify them later to better fine tune the tags closes #20

**Comment by Bornholio** [comment]
http://imgur.com/lPLN9w0 testings done on my system

**Comment by stratochief66** [comment]
@Bornholio The tag additions make sense to me, But why make all the intake parts & engines the same size? Intakes with less capacity are lighter and smaller (sizing was just a guesstimate, but IMO better than all being identical) and same with engines. Am I missing something obvious?

**Comment by Bornholio** [comment]
The intake part models snap into the hexcore shape. This https://i.imgur.com/yUctg5A.png shows one of the other parts snapped into it. It looked as if they were all three intended to snap into these frames just like the other items of their same shape.
As for the engines I didn't make any change except tags and gauges.
My album of ISRU Part stats in VAB https://imgur.com/a/dHeAr

**Pull request merged**
